version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: biblioteca_user
      POSTGRES_PASSWORD: biblioteca_pass
      POSTGRES_DB: biblioteca_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://biblioteca_user:biblioteca_pass@db:5432/biblioteca_db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
